services:
  - type: web
    name: baby-clothing-store
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: baby-store-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true

databases:
  - name: baby-store-db
    plan: free